
const idValues = {

    'TYPE_PASSPORT' : 'PASSPORT',
    'TYPE_NATIONAL_ID'  :'NATIONAL ID',
    'TYPE_SSNIT'  :'SSNIT',
    'TYPE_VOTER_CARD'  :'VOTER CARD',
    'TYPE_VOTER_ID'  :'VOTER_ID',
    'TYPE_ALIEN_CARD'  :'ALIEN_CARD',
    'TYPE_BVN'  :'BVN',
    'TYPE_NIN'  :'NIN',
    'TYPE_NIN_SLIP'  :'NIN_SLIP',
    'TYPE_DRIVERS_LICENSE'  :'DRIVER LICENSE',
    'TYPE_TIN'  :'TIN',
    'TYPE_CAC'  :'CAC',
    'NATIONAL_ID_NO_PHOTO'  :'NATIONAL_ID_NO_PHOTO',
    'TELCO_SUBSCRIBER'  : 'TELCO SUBSCRIBER',
    'TYPE_CUSTOMER_PROFILE'  :'CUSTOMER_PROFILE',
    'TYPE_KRA' : 'KRA'
        
} 

module.exports = {
    idValues
}